// ignore_for_file: constant_identifier_names

part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const SIGN_SELECTECTION = _Paths.SIGN_SELECTECTION;
  static const SIGN_IN = _Paths.SIGN_IN;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const ACCOUNT_CREATE_SUCCESS = _Paths.ACCOUNT_CREATE_SUCCESS;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const PASSWORD_RESETED = _Paths.PASSWORD_RESETED;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const BOTTOM_BAR = _Paths.BOTTOM_BAR;
  static const CHAT_VIEW = _Paths.CHAT_VIEW;
  static const ORDER = _Paths.ORDER;
  static const PROFILE = _Paths.PROFILE;
  static const GET_QUOTE = _Paths.GET_QUOTE;
  static const GET_QUOTE_TWO = _Paths.GET_QUOTE_TWO;
  static const GET_QUOTE_THREE = _Paths.GET_QUOTE_THREE;
  static const GET_QUOTE_FOUR = _Paths.GET_QUOTE_FOUR;
  static const GET_QUOTE_FIVE = _Paths.GET_QUOTE_FIVE;
  static const GET_QUOTE_SIX = _Paths.GET_QUOTE_SIX;
  static const GET_QUOTE_SEVEN = _Paths.GET_QUOTE_SEVEN;
  static const GET_QUOTE_NINE = _Paths.GET_QUOTE_NINE;
  static const GET_QUOTE_EIGHT = _Paths.GET_QUOTE_EIGHT;
  static const GET_QUOTE_ON_THE_WAY = _Paths.GET_QUOTE_ON_THE_WAY;
  static const PROJECT_DETAILS = _Paths.PROJECT_DETAILS;
  static const CHECK_OUT = _Paths.CHECK_OUT;
  static const ADD_NEW_CARD = _Paths.ADD_NEW_CARD;
  static const EDITOR_ALOTTED = _Paths.EDITOR_ALOTTED;
  static const IN_PROGRESS = _Paths.IN_PROGRESS;
  static const COMPLETED = _Paths.COMPLETED;
  static const QUOTE_GIVEN = _Paths.QUOTE_GIVEN;
  static const SEND_MESSAGE = _Paths.SEND_MESSAGE;
  static const BOTTOM_PROFILE = _Paths.BOTTOM_PROFILE;
  static const ACCOUNT_SETTING = _Paths.ACCOUNT_SETTING;
  static const PAYMENT_AND_DEPOSIT = _Paths.PAYMENT_AND_DEPOSIT;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const REWARDS = _Paths.REWARDS;
  static const GET_REWARD = _Paths.GET_REWARD;
  static const GET_REWARD_TWO = _Paths.GET_REWARD_TWO;
  static const FIND_AN_EDITOR = _Paths.FIND_AN_EDITOR;
  static const EDITOR_BOTTOM_BAR = _Paths.EDITOR_BOTTOM_BAR;
  static const EDITOR_CHATS = _Paths.EDITOR_CHATS;
  static const EDITOR_PROFILE = _Paths.EDITOR_PROFILE;
  static const EDITOR_SIGN_UP = _Paths.EDITOR_SIGN_UP;
  static const EDITOR_ACCOUN_SUCCESS = _Paths.EDITOR_ACCOUN_SUCCESS;
  static const EDITOR_SIGN_IN = _Paths.EDITOR_SIGN_IN;
  static const EDITOR_SEND_MESSAGE = _Paths.EDITOR_SEND_MESSAGE;
  static const EDITOR_ORDERS = _Paths.EDITOR_ORDERS;
  static const EDITOR_IN_PROGRESS = _Paths.EDITOR_IN_PROGRESS;
  static const EDITOR_DELIVER = _Paths.EDITOR_DELIVER;
  static const EDITOR_PROFILE_EDIT = _Paths.EDITOR_PROFILE_EDIT;
  static const EDITOR_WITHDRAW = _Paths.EDITOR_WITHDRAW;
  static const EDITOR_ADD_PAYMENT_METHOD = _Paths.EDITOR_ADD_PAYMENT_METHOD;
  static const EDITOR_NOTIFICATION = _Paths.EDITOR_NOTIFICATION;
  static const ORDER_COMPLETED = _Paths.ORDER_COMPLETED;
  static const EDITOR_REWARD = _Paths.EDITOR_REWARD;
  static const OTP_CONFIRMATION = _Paths.OTP_CONFIRMATION;
  static const RESET_OTP_CONFIRMATION = _Paths.RESET_OTP_CONFIRMATION;
  static const EDITOR_PROJECT_DETAILS = _Paths.EDITOR_PROJECT_DETAILS;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const SIGN_SELECTECTION = '/sign-selectection';
  static const SIGN_IN = '/sign-in';
  static const SIGN_UP = '/sign-up';
  static const ACCOUNT_CREATE_SUCCESS = '/account-create-success';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const PASSWORD_RESETED = '/password-reseted';
  static const CHANGE_PASSWORD = '/change-password';
  static const BOTTOM_BAR = '/bottom-bar';
  static const CHAT_VIEW = '/chat-view';
  static const ORDER = '/order';
  static const PROFILE = '/profile';
  static const GET_QUOTE = '/get-quote';
  static const GET_QUOTE_TWO = '/get-quote-two';
  static const GET_QUOTE_THREE = '/get-quote-three';
  static const GET_QUOTE_FOUR = '/get-quote-four';
  static const GET_QUOTE_FIVE = '/get-quote-five';
  static const GET_QUOTE_SIX = '/get-quote-six';
  static const GET_QUOTE_SEVEN = '/get-quote-seven';
  static const GET_QUOTE_NINE = '/get-quote-nine';
  static const GET_QUOTE_EIGHT = '/get-quote-eight';
  static const GET_QUOTE_ON_THE_WAY = '/get-quote-on-the-way';
  static const PROJECT_DETAILS = '/project-details';
  static const EDITOR_PROJECT_DETAILS = '/editor-project-details';
  static const CHECK_OUT = '/check-out';
  static const ADD_NEW_CARD = '/add-new-card';
  static const EDITOR_ALOTTED = '/editor-alotted';
  static const IN_PROGRESS = '/in-progress';
  static const COMPLETED = '/completed';
  static const SEND_MESSAGE = '/send-message';
  static const BOTTOM_PROFILE = '/bottom-profile';
  static const ACCOUNT_SETTING = '/account-setting';
  static const PAYMENT_AND_DEPOSIT = '/payment-and-deposit';
  static const NOTIFICATIONS = '/notifications';
  static const REWARDS = '/rewards';
  static const GET_REWARD = '/get-reward';
  static const GET_REWARD_TWO = '/get-reward-two';
  static const FIND_AN_EDITOR = '/find-an-editor';
  static const EDITOR_BOTTOM_BAR = '/editor-bottom-bar';
  static const EDITOR_CHATS = '/editor-chats';
  static const EDITOR_PROFILE = '/editor-profile';
  static const EDITOR_SIGN_UP = '/editor-sign-up';
  static const EDITOR_ACCOUN_SUCCESS = '/editor-accoun-success';
  static const EDITOR_SIGN_IN = '/editor-sign-in';
  static const EDITOR_SEND_MESSAGE = '/editor-send-message';
  static const EDITOR_ORDERS = '/editor-orders';
  static const EDITOR_IN_PROGRESS = '/editor-in-progress';
  static const EDITOR_DELIVER = '/editor-deliver';
  static const EDITOR_PROFILE_EDIT = '/editor-profile-edit';
  static const EDITOR_WITHDRAW = '/editor-withdraw';
  static const EDITOR_ADD_PAYMENT_METHOD = '/editor-add-payment-method';
  static const EDITOR_NOTIFICATION = '/editor-notification';
  static const ORDER_COMPLETED = '/order-completed';
  static const EDITOR_REWARD = '/editor-reward';
  static const OTP_CONFIRMATION = '/otp-confirmation';
  static const QUOTE_GIVEN = '/quote-given';
  static const RESET_OTP_CONFIRMATION = '/reset-otp-confirmation';
}
